version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: connect-shiksha-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: connect-shiksha-crm
    volumes:
      - mongodb_data:/data/db
    networks:
      - connect-shiksha-network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: connect-shiksha-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:admin123@mongodb:27017/connect-shiksha-crm?authSource=admin
      JWT_SECRET: your_super_secret_jwt_key_change_in_production
      JWT_EXPIRE: 7d
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      CLIENT_URL: http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - connect-shiksha-network
    volumes:
      - ./uploads:/app/uploads

  # Frontend (Next.js)
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: connect-shiksha-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - connect-shiksha-network

volumes:
  mongodb_data:
    driver: local

networks:
  connect-shiksha-network:
    driver: bridge

